### ISSUE TITLE
開発環境・CI/CDセットアップ

### ISSUE THREAD

**Issue by cycling777** [w-pinkietech/iot4-copy#15]
## 概要
モダンなPython開発環境とCI/CDパイプラインを構築し、品質の高いテスト駆動開発を実現する。

## 背景
現行Node-REDシステムではテストが全く存在せず、品質管理が課題だった。新システムでは最初からTDD・CI/CDを導入し、製造業IoTに求められる信頼性を確保する。

### 開発環境
- [ ] **uv**によるPython環境管理（Python 3.11）
- [ ] **pyproject.toml**でのプロジェクト設定
- [ ] **VSCode**設定ファイル（.vscode/）
- [ ] **Docker**開発環境（docker-compose.dev.yml）

### テスト環境
- [ ] **pytest**設定（pytest.ini）
- [ ] **pytest-cov**によるカバレッジ測定
- [ ] **pytest-asyncio**（非同期テスト）
- [ ] **pytest-mock**（モック戦略）

### 品質管理ツール
- [ ] **pre-commit hooks**設定
  - black（フォーマッター）
  - ruff（高速リンター）
  - mypy（型チェック）
  - yamllint（YAML検証）
  - bandit（セキュリティ）
- [ ] **commitizen**（コミットメッセージ規約）

### CI/CDパイプライン
- [ ] **GitHub Actions**設定
  - PRごとの自動テスト
  - コードカバレッジレポート
  - 型チェック・リンター
  - セキュリティスキャン
- [ ] **Raspberry Pi向けビルド**
  - ARM64対応Dockerイメージ
  - 自動デプロイ（将来拡張）

### pyproject.toml
```toml
[project]
name = "iot-gateway"
version = "0.1.0"
requires-python = ">=3.11"

[tool.pytest.ini_options]
minversion = "7.0"
testpaths = ["tests"]
asyncio_mode = "auto"

[tool.coverage.run]
source = ["src"]
omit = ["*/tests/*"]

[tool.mypy]
python_version = "3.11"
strict = true
```

### .pre-commit-config.yaml
```yaml
repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
  
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
  
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
```

## 成果物
- [ ] 開発環境セットアップスクリプト
- [ ] 開発環境ドキュメント（README_DEV.md）
- [ ] CI/CD設定ファイル群
- [ ] サンプルテストコード
- [ ] コントリビューションガイド

## 検証項目
- [ ] 新規開発者が10分以内に環境構築完了
- [ ] 全テストが3分以内に実行完了
- [ ] カバレッジ80%以上を維持
- [ ] pre-commit hooksが正常動作

## 関連Issue
- #12 Modbusプラグイン実装（最初のTDD対象）
- 後続: BravePIプラグイン実装

---
**Priority**: High  
**Estimated Duration**: 1週間

Labels: new-system, feature, high, mvp
