### ISSUE TITLE
Modbusプラグイン実装計画の策定

### ISSUE THREAD

**Issue by cycling777** [w-pinkietech/iot4-copy#6]
## 概要
2層プラグインアーキテクチャの実証として、最初に実装するModbusプロトコルプラグインの詳細な実装計画を策定する。

## 背景
Modbusは業界標準プロトコルであり、実装例・ライブラリが豊富なため、プラグインアーキテクチャの最初の実装として最適。この実装を通じてプラグイン開発のベストプラクティスを確立する。

### Modbusプロトコル仕様
- **Modbus TCP**: Ethernet経由、ポート502
- **Modbus RTU**: シリアル通信（RS485/RS232）
- **機能コード**: 03（Read Holding Registers）、04（Read Input Registers）を優先実装
- **データ型**: 16bit整数、32bit整数、32bit浮動小数点

### 対象デバイス例
- 温度調節器（オムロン、横河等）
- 電力計（三菱、シュナイダー等）
- 汎用PLC（各社Modbusゲートウェイ）

### Phase 1: ハードウェアドライバ層
- [ ] **TCP/IPドライバ実装**
  - Socket通信基底クラス
  - 接続管理（connect/disconnect）
  - タイムアウト・リトライ処理
  - 接続プール機能

- [ ] **シリアル通信ドライバ実装**
  - PySerial基底クラス
  - ポート設定（ボーレート、パリティ等）
  - CRC計算・検証
  - 送受信バッファ管理

### Phase 2: プロトコルプラグイン層
- [ ] **Modbusプロトコル変換実装**
  - ADU（Application Data Unit）構築
  - 機能コード03/04の実装
  - レジスタアドレス管理
  - データ型変換（int16→float32等）

- [ ] **統一データモデル変換**
  - 生データ→DeviceDataクラス変換
  - 品質情報設定（通信成功/失敗）
  - タイムスタンプ生成
  - メタデータ付与

### Phase 3: 設定・エラーハンドリング
- [ ] **設定ファイル対応**
  - YAML設定の解析
  - デバイス設定バリデーション
  - データポイント設定管理
  - 動的設定変更対応

- [ ] **エラーハンドリング**
  - Modbusエラーコード処理
  - 通信エラー（タイムアウト、接続断）
  - データ変換エラー
  - 設定エラー

### Phase 4: テスト・検証
- [ ] **単体テスト**
  - モック通信でのテスト
  - 各機能コードのテスト
  - エラーケースのテスト
  - パフォーマンステスト

- [ ] **結合テスト**
  - 実機器との通信テスト
  - 長時間稼働テスト
  - 複数デバイス同時接続テスト
  - 障害回復テスト

### 使用ライブラリ
- **pymodbus**: Pythonの代表的Modbusライブラリ
- **asyncio**: 非同期通信による高効率化
- **pydantic**: 設定データのバリデーション
- **structlog**: 構造化ログ出力

### 設計パターン
- **Factory Pattern**: プラグイン生成
- **Strategy Pattern**: TCP/RTU切り替え
- **Observer Pattern**: データ通知
- **Circuit Breaker**: 障害隔離

### TCP接続設定
```yaml
- id: modbus_temp_001
  protocol: modbus
  plugin: official/modbus
  connection:
    type: tcp
    host: 192.168.1.100
    port: 502
    timeout: 1000
  data_points:
    - address: 40001
      name: temperature
      type: float32
      scale: 0.1
```

### RTU接続設定
```yaml
- id: modbus_power_001
  protocol: modbus
  plugin: official/modbus
  connection:
    type: rtu
    port: /dev/ttyUSB0
    baudrate: 9600
    bytesize: 8
    parity: 'N'
    stopbits: 1
  data_points:
    - address: 30001
      name: power_consumption
      type: uint32
```

## 成果物
- [ ] Modbusプラグイン実装コード
- [ ] ハードウェアドライバ基底クラス
- [ ] プロトコルプラグイン基底クラス
- [ ] 単体・結合テストスイート
- [ ] 設定リファレンス
- [ ] プラグイン開発ガイド

## 検証項目
- [ ] 実機器での動作確認（最低3機種）
- [ ] 24時間連続稼働テスト
- [ ] 複数デバイス（10台）同時接続テスト
- [ ] 通信エラー時の復旧性能
- [ ] 設定変更の即座反映

## 関連Issue
- 統一データモデル: #4
- 全体アーキテクチャ: #5
- 設定ファイルスキーマ: 後続Issue
- エラーハンドリング戦略: 後続Issue

---
**Priority**: Medium  
**Estimated Duration**: 2-3週間
