### ISSUE TITLE
YAML設定ファイルのスキーマ定義・バリデーション実装

### ISSUE THREAD

**Issue by cycling777** [w-pinkietech/iot4-copy#7]
## 概要
デバイス設定・システム設定のYAMLファイル形式について、詳細なスキーマ定義とバリデーション機能を実装する。

## 背景
現在のMVP技術仕様書にはYAML設定例が記載されているが、正式なスキーマ定義とバリデーション機能が不足している。製造業現場での運用を考慮すると、設定ミスの早期発見とエラーメッセージの分かりやすさが重要。

### 1. デバイス設定スキーマ（devices.yaml）
- [ ] **基本デバイス情報**
  - id（必須、ユニーク制約）
  - name（表示名）
  - enabled（有効/無効）
  - protocol（プロトコル種別）
  - plugin（プラグイン指定）

- [ ] **接続設定**
  - TCP/IP接続（host、port、timeout）
  - シリアル接続（port、baudrate、parity等）
  - UART接続（BravePI専用）
  - 認証情報（必要に応じて）

- [ ] **データポイント設定**
  - アドレス・デバイスコード
  - データ型・変換設定
  - 単位・スケール設定
  - サンプリング設定

- [ ] **ポーリング設定**
  - 間隔・リトライ設定
  - タイムアウト設定
  - エラー時の動作

### 2. システム設定スキーマ（system.yaml）
- [ ] **データベース設定**
  - InfluxDB接続情報
  - MariaDB接続情報
  - 接続プール設定

- [ ] **MQTT設定**
  - ブローカー情報
  - トピック設計
  - QoS設定

- [ ] **ログ設定**
  - ログレベル・出力先
  - 構造化ログ設定
  - ローテーション設定

- [ ] **プラグイン設定**
  - プラグインディレクトリ
  - ロード設定
  - セキュリティ設定

### 3. プラグイン固有設定
- [ ] **Modbusプラグイン設定**
- [ ] **MCプロトコルプラグイン設定**
- [ ] **BravePIプラグイン設定**

### スキーマ定義
- [ ] **JSON Schema形式**での厳密な定義
- [ ] **Pydantic**モデルでの実装
- [ ] **型安全性**の確保
- [ ] **デフォルト値**の適切な設定

### バリデーション機能
- [ ] **設定ファイル読み込み時**の自動バリデーション
- [ ] **リアルタイム設定変更時**のバリデーション
- [ ] **依存関係チェック**（例：プラグインの存在確認）
- [ ] **範囲チェック**（ポート番号、IPアドレス等）

### エラーハンドリング
- [ ] **分かりやすいエラーメッセージ**
- [ ] **エラー箇所の特定**（行番号、フィールド名）
- [ ] **修正提案**の表示
- [ ] **警告レベル**の分類

### 設定管理機能
- [ ] **設定変更の検知**
- [ ] **設定リロード**機能
- [ ] **設定バックアップ**機能
- [ ] **設定差分表示**機能

### 必須バリデーション
- [ ] ID重複チェック
- [ ] IPアドレス形式チェック
- [ ] ポート番号範囲チェック（1-65535）
- [ ] ファイルパス存在チェック
- [ ] プラグイン存在チェック

### プロトコル固有バリデーション
- [ ] **Modbus**: レジスタアドレス範囲（1-65535）
- [ ] **MCプロトコル**: デバイスコード形式（D、M等）
- [ ] **BravePI**: デバイスID形式（16進文字列）

### 依存関係バリデーション
- [ ] 指定プラグインの存在確認
- [ ] データベース接続設定の整合性
- [ ] ネットワーク設定の妥当性

### Phase 1: 基本スキーマ定義
- [ ] JSON Schema作成
- [ ] Pydanticモデル実装
- [ ] 基本バリデーション機能
- [ ] 単体テスト作成

### Phase 2: 高度なバリデーション
- [ ] 依存関係チェック実装
- [ ] カスタムバリデータ作成
- [ ] エラーメッセージ改善
- [ ] 設定変更検知機能

### Phase 3: 運用機能
- [ ] 設定管理UI（React）
- [ ] 設定バックアップ・復元
- [ ] 設定差分・履歴管理
- [ ] 設定テンプレート機能

## 成果物
- [ ] JSON Schema定義ファイル群
- [ ] Pydanticモデルライブラリ
- [ ] バリデーション機能実装
- [ ] 設定管理CLI/API
- [ ] 設定ファイル例・テンプレート
- [ ] バリデーションテストスイート
- [ ] 設定リファレンスドキュメント

### 正常ケース
```yaml
# 有効な設定例
devices:
  - id: valid_device
    name: "正常なデバイス"
    enabled: true
    protocol: modbus
    connection:
      type: tcp
      host: "192.168.1.100"
      port: 502
```

### エラーケース
```yaml
# 無効な設定例とエラーメッセージ
devices:
  - id: "invalid device"  # スペース含むID → エラー
    port: 70000           # ポート範囲外 → エラー
    protocol: unknown     # 未対応プロトコル → エラー
```

## 関連Issue
- 統一データモデル: #4
- Modbusプラグイン実装: #6
- エラーハンドリング戦略: 後続Issue

---
**Priority**: Medium  
**Estimated Duration**: 1-2週間
